#!/usr/bin/env bash
# shellcheck disable=SC2086

PY_FILES=$(git diff --name-only --cached --diff-filter=ACMR | grep "\.py$")

set -eo pipefail

if [[ -n "$PY_FILES" ]]; then
    # set up the virtualenv if it's not already available
    if [[ ! -v VIRTUAL_ENV ]]; then
        source .venv/bin/activate
    fi
    echo "Checking:"
    echo "$PY_FILES"
    # Run black against changed python files for this commit
    black --check --diff ${PY_FILES//$'\n'/ }
    # Run ruff (against all files, it's fast enough)
    ruff check . --diff && echo "ruff passed!"
else
    exit 0
fi

exit 0
