#!/bin/bash
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# admin user
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-monitor-hardening/admin_user || true
    db_go || true
    db_get securedrop-monitor-hardening/admin_user
    if [ -n "$RET" ]; then
        if [ "$(getent passwd $RET)" ]; then
            ok=1
        else
            db_input critical securedrop-monitor-hardening/admin_user_continue || true
            db_go || true
            db_get securedrop-monitor-hardening/admin_user_continue
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-monitor-hardening/admin_user seen false
            fi
        fi
    fi
done

# Get App server's IP
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-monitor-hardening/app_ip || true
    db_go || true
    db_get securedrop-monitor-hardening/app_ip
    IP="$RET"
    if [[ "$IP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        IP=($IP)
        IFS=$OIFS
        [[ ${IP[0]} -le 255 && ${IP[1]} -le 255 && ${IP[2]} -le 255 && ${IP[3]} -le 255 ]]
        ok=1
    else
        db_input critical securedrop-monitor-hardening/app_ip_continue || true
        db_go || true
        db_get securedrop-monitor-hardening/app_ip_continue
        if [ "$RET" = "false" ]; then
            exit 1
        else
            db_fset securedrop-monitor-hardening/app_ip seen false
        fi
    fi
done

# continue after all the questions
db_go || true
