FROM circleci/python:2

COPY securedrop/requirements securedrop/requirements
RUN sudo pip install -r securedrop/requirements/develop-requirements.txt

WORKDIR /src
COPY . /src

CMD ["sudo", "make", "--keep-going", "lint"]
