#!/bin/bash
# this is for backward compatibility and also because it
# is more convenient for the admin to have the script at
# the top level of the SecureDrop repository
exec securedrop/securedrop-admin "$@"
