---
- name: Check for site specific file
  stat:
    path: "{{ config_path }}/site-specific"
  register: site_specific_file

- name: Import variables
  include_vars: "{{ config_path }}/site-specific"
  when: site_specific_file.stat.exists

- name: Create the SecureDrop GNOME Shell Extension directories
  file:
    state: directory
    path: "{{ item }}"
  with_items: "{{ tails_config_extension_directories }}"

- name: Set normal user ownership on subset of directories.
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    owner: amnesia
    group: amnesia
  # Only set normal user ownership for files in ~amnesia.
  when: item.startswith(tails_config_amnesia_home)
  with_items: "{{ tails_config_extension_directories }}"

- name: Copy the extension metadata to the extension directory in Persistent Storage
  become: yes
  copy:
    src: securedrop@securedrop.freedom.press/metadata.json
    dest: "{{ tails_config_live_dotfiles }}/.local/share/gnome-shell/extensions/securedrop@securedrop.freedom.press/"
    owner: amnesia
    group: amnesia

- name: Copy the extension CSS to the extension directory in Persistent Storage
  become: yes
  copy:
    src: securedrop@securedrop.freedom.press/stylesheet.css
    dest: "{{ tails_config_live_dotfiles }}/.local/share/gnome-shell/extensions/securedrop@securedrop.freedom.press/"
    owner: amnesia
    group: amnesia

- name: Copy the symbolic icon used for the shell extension in Persistent Storage
  become: yes
  copy:
    src: securedrop-symbolic.png
    dest: "{{ tails_config_live_dotfiles }}/.local/share/gnome-shell/extensions/securedrop@securedrop.freedom.press/icons/"
    owner: amnesia
    group: amnesia

- name: Assemble interface information for extension
  set_fact:
    _securedrop_extension_info:
      - src: extension.js.in
        filename: extension.js

- name: Create SecureDrop extension
  become: yes
  template:
    src: "{{ item.0.src }}"
    dest: "{{ item.1 }}/{{ item.0.filename }}"
    owner: amnesia
    group: amnesia
    mode: "0700"
  with_nested:
    - "{{ _securedrop_extension_info }}"
    - "{{ tails_config_extension_directories }}"

- name: Add extension translations in Persistent Storage
  synchronize:
    src: roles/tails-config/templates/locale/
    dest: "{{ tails_config_live_dotfiles }}/.local/share/gnome-shell/extensions/securedrop@securedrop.freedom.press/locale/"
