#!/bin/sh
# Description: apply the securedrop iptable rules
if [ -f /etc/network/iptables/rules_v4 ]; then
  iptables-restore < /etc/network/iptables/rules_v4
elif [ -f /etc/iptables/rules.v4 ]; then
  iptables-restore < /etc/iptables/rules.v4
else
  echo "Iptables rules file does not exist"
  exit 1
fi

if [ -f /etc/network/iptables/rules_v6 ]; then
  ip6tables-restore < /etc/network/iptables/rules_v6
elif [ -f /etc/iptables/rules.v6 ]; then
  ip6tables-restore < /etc/iptables/rules.v6
else
  echo "Ip6tables rules file does not exist"
  exit 1
fi

exit 0
