require 'rake'
require 'rspec/core/rake_task'


task :spec    => 'spec:all'
task :default => :spec

# this function accepts a hostname and returns a hash
# that includes roles assigned to that host. changes made
# in ansible config must be manually duplicated here.
def roles(host)
  roles = [ "all" ]
  case host
  when /-staging$/
    roles << "common-staging"
  when /^development$/
    roles << "development"
  when /^build$/
    roles << "build"
  when /^app-staging$/
    roles << "app-staging"
  when /^mon-staging$/
    roles << "mon-staging"
  end
  roles
end


# manually declare hosts, and assign them roles for testing
hosts = %w(development build app-staging mon-staging).map do |host|
  {
    :name => host,
    :roles => roles(host)
  }
end


namespace :spec do
  targets = []
  Dir.glob('./spec/development').each do |dir|
    next unless File.directory?(dir)
    target = File.basename(dir)
    target = "_#{target}" if target == "default"
    targets << target
  end

  task :all     => targets
  task :default => :all

  targets.each do |target|
    original_target = target == "_default" ? target[1..-1] : target
    desc "Run serverspec tests to #{original_target}"
    RSpec::Core::RakeTask.new(target.to_sym) do |t|
      ENV['TARGET_HOST'] = original_target
      t.pattern = "spec/#{original_target}/*_spec.rb"
    end
  end
end


