require 'rake'
require 'rspec/core/rake_task'


task :spec    => 'spec:all'
task :staging => 'spec:staging'
task :default => :spec

# this function accepts a hostname and returns a hash
# that includes roles assigned to that host. changes made
# in ansible config must be manually duplicated here.
def roles(host)
  roles = []
  case host
  when /^development$/
    (roles << %w(common-development development)).flatten!
  when /^build$/
    (roles << "build").flatten!
  when /^app-staging/
    (roles << %w(common-development common-staging app-staging grsecurity)).flatten!
  when /^mon-staging/
    (roles << %w(common-staging mon-staging grsecurity)).flatten!
  end

  # DigitalOcean droplets don't support custom kernels, so remove
  # any planned spectests for grsecurity. This is only relevant
  # for the app and mon hosts, so don't delay other tests with check.
  if host.match(/^(app|mon)/)
    if `vagrant status #{host} --machine-readable`.match(/#{host},provider-name,digital_ocean/m)
      roles.delete('grsecurity')
    end
  end
  roles
end


# manually declare hosts, and assign them roles for testing
hosts = %w(development build app-staging mon-staging).map do |host|
  {
    :name => host,
    :roles => roles(host)
  }
end


# dynamically determine roles per host
# this brilliant pragma conceived by @vincentbernat, see
# https://github.com/vincentbernat/serverspec-example
# http://vincent.bernat.im/en/blog/2014-serverspec-test-infrastructure.html
namespace :spec do
  # assign all hosts to serverspec task run
  task :all => hosts.map { |h| h[:name] }

  # assign only /staging/ hosts to serverspec task run
  task :staging => hosts.select{ |h| h[:name].match(/staging$/) }.map{ |h| h[:name] }

  hosts.each do |host|
    desc "Run spectests against #{host[:name]}"
    RSpec::Core::RakeTask.new(host[:name].to_sym) do |t|
      ENV['TARGET_HOST'] = host[:name]
      t.pattern = './spec/{' + host[:roles].join(",") + '}/*_spec.rb'
      puts "Running spectests for host '#{host[:name]}'..."
      t.verbose = false
    end
  end
end
