#!/bin/bash
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Get the destination email address for ossec alerts
#TODO validate
db_input critical securedrop-monitor-ossec/get_email || true

ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-monitor-ossec/ossec_key_list || true
    db_go || true
    db_get securedrop-monitor-ossec/ossec_key_list
    if [ -f "$RET" ]; then
        ok="1"
    else
    # TODO validate that keys create date is valid
        if [ ! -f "$RET" ]; then
            db_input critical securedrop-monitor-ossec/ossec_key_list_continue || true
            db_go || true
            db_get securedrop-monitor-ossec/ossec_key_list_continue || true
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-monitor-ossec/ossec_key_list seen false
            fi
        fi
    fi
done

# continue after all the questions
db_go || true
