#!/bin/sh
# postinst script for securedrop-config-focal

set -e
set -x

# Issue #5782
# Set Prompt=never for distro upgrades
update_release_prompt() {
    set -e
    upgrade_config='/etc/update-manager/release-upgrades'
    sed -i 's/Prompt=.*/Prompt=never/' "$upgrade_config"
}

case "$1" in
    configure)
    update_release_prompt

    # Configuration required for cron-apt
    rm -f /etc/cron-apt/action.d/3-download
    cp /opt/securedrop/cron-apt/0-update /etc/cron-apt/action.d/
    cp /opt/securedrop/cron-apt/5-upgrade /etc/cron-apt/action.d/
    cp /opt/securedrop/cron-apt/9-remove /etc/cron-apt/action.d/
    cp /opt/securedrop/cron-apt/cron-apt-config /etc/cron-apt/config

    cp /opt/securedrop/80securedrop /etc/apt/apt.conf.d/

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
