#!/bin/bash
# Wrapper script to determine which VM driver is appropriate for the staging
# environment, given the host OS and available tooling. Supports:
#
#   * VirtualBox (the default)
#   * Libvirt/KVM
#   * Qubes (via Admin API)
#
# Set the VAGRANT_DEFAULT_PROVIDER env var to override autodetection.

set -e
set -o pipefail

. ./devops/scripts/boot-strap-venv.sh

securedrop_staging_scenario="$(./devops/scripts/select-staging-env)"

printf "Creating staging environment via '%s'...\n" "${securedrop_staging_scenario}"

# Run it!
virtualenv_bootstrap
# Are we in CI? Then lets do full testing post install!
if [ "$USER" = "sdci" ]; then
    molecule test -s "${securedrop_staging_scenario}"
else
    molecule converge -s "${securedrop_staging_scenario}"
fi
