#!/bin/bash
# Wrapper script to create Vagrant boxes for use with the "upgrade"
# scenario. The call to `package.py` is not handled within Molecule,
# due to the need to prompt interactively for sudo password during
# box creation.
set -e
set -u
set -o pipefail


echo '######################'
echo 'Building Xenial boxes'
echo '######################'
molecule test -s vagrant-packager
molecule/vagrant-packager/package.py
molecule destroy -s vagrant-packager

