---
- include_tasks: "{{ role_path }}/../validate/tasks/validate_qubes_environment.yml"

- include_tasks: configure_tor.yml

- include_tasks: create_sdw_config.yml

- include_tasks: create_ssh_aliases.yml
