#!/bin/sh
# OSSEC	        Controls OSSEC HIDS
# Author:       Daniel B. Cid <dcid@ossec.net>
# Modified for slackware by Jack S. Lai
# Modified for securedrop by James Dolan

### BEGIN INIT INFO
# Provides:          SecureDrop App Server's OSSEC agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

. /lib/lsb/init-functions
. /etc/ossec-init.conf

if [ "X${DIRECTORY}" = "X" ]; then
    DIRECTORY="/var/ossec"
fi

    
start() {
	${DIRECTORY}/bin/ossec-control start
}

stop() {
	${DIRECTORY}/bin/ossec-control stop
}

status() {
	${DIRECTORY}/bin/ossec-control status
}


case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart)
	stop
	start
	;;
  status)
        status
	;;
  force-reload)
        stop
        start
        ;;
  *)
	echo "*** Usage: $0 {start|stop|restart|status|force-reload}"
	exit 1
esac

exit 0
