#!/opt/venvs/securedrop-app-code/bin/python
"""
Verify PGP key file contains:

* a valid PGP key.
* one PGP key.
* a PGP key matching the specified fingerprint.

It creates a temporary GPG keyring, imports they key and verifies
that only the specified fingerprint was imported
"""

import argparse
import sys
from pathlib import Path

import redwood

parser = argparse.ArgumentParser(description="Verify PGP key file")
parser.add_argument("pubkey", type=Path, help="Public key file")
parser.add_argument("fingerprint", help="Fingerprint of key")
args = parser.parse_args()

pubkey = args.pubkey.read_text()

fingerprint = redwood.is_valid_public_key(pubkey)
if fingerprint == args.fingerprint:
    print("Success! Specified fingerprint matches pubkey file.")
    sys.exit(0)
else:
    print(f"Failed! Key contains {fingerprint}, not {args.fingerprint}")
    sys.exit(1)
