#!/bin/bash
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Tor info
db_input medium securedrop-app-hardening/tor_key_id || true
db_input medium securedrop-app-hardening/tor_key_fpr || true

# admin user
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-app-hardening/admin_user || true
    db_go || true
    db_get securedrop-app-hardening/admin_user
    if [ -n "$RET" ]; then
        if [ "$(getent passwd $RET)" ]; then
            ok=1
        else
            db_input critical securedrop-app-hardening/admin_user_continue || true
            db_go || true
            db_get securedrop-app-hardening/admin_user_continue
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-app-hardening/admin_user seen false
            fi
        fi
    fi
done

db_go || true
