#!/bin/bash
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Is this prod dev environment
db_input critical securedrop-app/prod_dev || true
db_go || true

# If not prod get what deb packages to install
db_get securedrop-app/prod_dev
if [ "$RET" = "false" ]; then
    ok=""
    while [ ! "$ok" ]; do
        db_input critical securedrop-app/source_deb || true
        db_go || true
        db_get securedrop-app/source_deb
        if [ -f "$RET" ]; then
            ok=1
        else
            db_input critical securedrop-app/source_deb_continue || true
            db_go || true
            db_get securedrop-app/source_deb_continue
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-app/source_deb seen false
            fi
        fi

    done

    ok=""
    while [ ! "$ok" ]; do
        db_input critical securedrop-app/document_deb || true
        db_go || true
        db_get securedrop-app/document_deb
        if [ -f "$RET" ]; then
            ok=1
        else
            db_input critical securedrop-app/document_deb_continue || true
            db_go || true
            db_get securedrop-app/document_deb_continue
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-app/document_deb seen false
            fi
         fi
    done
fi

# Get the full path to application public gpg key
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-app/find_key_path || true
    db_go || true
    db_get securedrop-app/find_key_path
    if [ -f "$RET" ]; then
        ok=1
        db_go || true
    else
        db_input critical securedrop-app/find_key_path_continue || true
        db_go || true
        db_get securedrop-app/find_key_path_continue
        if [ "$RET" = "false" ]; then
            exit 1
        else
            db_fset securedrop-app/find_key_path seen false
        fi
    fi
done

# extract gpg key's fingerprint save to to dh_db and subsititute 
# the fpr value in the verify_fingerprint template
db_get securedrop-app/find_key_path
find_key_path="$RET"
key_fpr="$( gpg --with-fingerprint $find_key_path | awk -F '=' '/Key fingerprint/ {print $2}' | sed 's/ //g')"
db_set securedrop-app/app_key_fpr "$key_fpr"
db_subst securedrop-app/verify_fingerprint KEY_FPR "$key_fpr"
db_go || true

db_input critical securedrop-app/verify_fingerprint || true
db_go || true
db_get securedrop-app/verify_fingerprint
if [ "$RET" = "false" ]; then
    exit 1
fi

# Have option to use custom headers
db_input high securedrop-app/use_custom_header_image || true
db_go || true

db_get securedrop-app/use_custom_header_image
use_header="$RET"
if [ "$use_header" = "true" ]; then
    ok=""
    while [ ! "$ok" ]; do
        db_input critical securedrop-app/custom_header_image_path || true
        db_go || true
        db_get securedrop-app/custom_header_image_path
        if [ -f "$RET" ]; then
            ok=1
            db_go || true
        else
            db_input critical securedrop-app/custom_header_image_path_continue || true
            db_go || true
            db_get securedrop-app/custom_header_image_path_continue
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-app/custom_header_image_path seen false
            fi
        fi
    done
fi

# The securedrop application user on the host system
db_input medium securedrop-app/app_user || true
db_input medium securedrop-app/app_gid || true
db_input medium securedrop-app/app_uid || true

# Tor info
db_input medium securedrop-app/tor_key_id || true
db_input medium securedrop-app/tor_key_fpr || true

# Journalist user for document interface
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-app/journalist_user || true
    db_go || true
    db_get securedrop-app/journalist_user
    if [[ "$RET" =~  ^[A-Za-z0-9_]+$ ]]; then
        ok=1
        db_go || true
    else
        db_input critical securedrop-app/journalist_user_continue || true
        db_go || true
        db_get securedrop-app/journalist_user_continue
        if [ "$RET" = "false" ]; then
            exit 1
        else
            db_fset securedrop-app/journalist_user seen false
        fi
    fi
done

# admin user
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-app/admin_user || true
    db_go || true
    db_get securedrop-app/admin_user
    if [ -n "$RET" ]; then
        if [ "$(getent passwd $RET)" ]; then
            ok=1
        else
            db_input critical securedrop-app/admin_user_continue || true
            db_go || true
            db_get securedrop-app/admin_user_continue
            if [ "$RET" = "false" ]; then
                exit 1
            else
                db_fset securedrop-app/admin_user seen false
            fi
        fi
    fi
done

# Get Monitor server's IP
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-app/monitor_ip || true
    db_go || true
    db_get securedrop-app/monitor_ip
    IP="$RET"
    if [[ "$IP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        IP=($IP)
        IFS=$OIFS
        [[ ${IP[0]} -le 255 && ${IP[1]} -le 255 && ${IP[2]} -le 255 && ${IP[3]} -le 255 ]]
        ok=1
    else
        db_input critical securedrop-app/monitor_ip_continue || true
        db_go || true
        db_get securedrop-app/monitor_ip_continue
        if [ "$RET" = "false" ]; then
            exit 1
        else
            db_fset securedrop-app/monitor_ip seen false
        fi
    fi
done

db_go || true
