# this file is concatonated onto Dockerfile for use in building a test image
RUN apt-get install -y firefox
RUN apt-get install -y git xvfb haveged curl gettext

# pinned firefox version for selenium compatibility. See bd795e2f5865b4f6e6e1b88bcbbacef704675c74
ENV FIREFOX_CHECKSUM=88d25053306d33658580973b063cd459a56e3596a3a298c1fb8ab1d52171d860
RUN curl -LO https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/+build/9727836/+files/firefox_46.0.1+build1-0ubuntu0.14.04.3_amd64.deb && \
    shasum -a 256 firefox*deb && \
    echo "${FIREFOX_CHECKSUM}  firefox_46.0.1+build1-0ubuntu0.14.04.3_amd64.deb" | shasum -a 256 -c - && \
       dpkg -i firefox*deb && apt-get install -f

RUN pip install -r requirements/test-requirements.txt

COPY . /app

RUN make test-config
RUN ./manage.py reset

CMD ["pytest"]
