#!/bin/bash
set -euo pipefail
set -x
export DISPLAY=:1
Xvfb :1 -screen 0 1024x768x24 -ac +extension GLX +render -noreset &
haveged &
redis-server &

echo -n 4096 > /proc/sys/kernel/random/write_wakeup_threshold

rm /dev/random
ln -s /dev/urandom /dev/random

touch tests/log/firefox.log
function cleanup {
  cp tests/log/firefox.log /tmp/test-results/logs/
}
trap cleanup EXIT

mkdir -p "/tmp/test-results/logs"

export PAGE_LAYOUT_LOCALES="en_US,ar,fr_FR"
pytest \
  --page-layout \
  --durations 10 \
  --junitxml=/tmp/test-results/junit.xml \
  --cov-report html:/tmp/test-results/cov_html \
  --cov-report xml:/tmp/test-results/cov.xml \
  --cov-report annotate:/tmp/test-results/cov_annotate \
  --cov=. \
  "$@"
