name    'deaddrop-ossec'
version '0.1.0'
source 'UNKNOWN'
author 'deaddrop'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
