#!/bin/sh
# Description: apply the securedrop iptable rules
if [ -f /etc/iptables/rules_v4 ]; then
  iptables-restore < /etc/iptables/rules_v4
else
  echo "Iptables rules file does not exist"
  exit 1
fi
exit 0
