#!/bin/sh
set -e

# Set PaX flags on GRUB binaries. Required when running under a grsec kernel,
# i.e. during kernel upgrades. If the GRUB binaries do not have the proper flags,
# the kernel image will fail to install.
#
# This script must run prior to the `zz-update-grub` kernel postinst hook,
# which will happen automatically due to sorting of the postinst scripts.
#
# Enabling EMUTRAMP on grub binaries, which requires `CONFIG_PAX_EMUTRAMP=y`
# to be set in the kernel config. Using `-z` to clear out any other flags,
# so the binaries will get only the intended settings, and all others
# not maintained by this script will be removed.
paxctl -zCE /usr/sbin/grub-probe
paxctl -zCE /usr/sbin/grub-mkdevicemap
paxctl -zCE /usr/bin/grub-script-check
