"""unique_index_for_instanceconfig_valid_until

Revision ID: 1ddb81fb88c2
Revises: 92fba0be98e9
Create Date: 2021-06-04 17:28:25.725563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddb81fb88c2'
down_revision = 'b060f38c0c31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.create_index('ix_one_active_instance_config', [sa.text('valid_until IS NULL')], unique=True, sqlite_where=sa.text('valid_until IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance_config', schema=None) as batch_op:
        batch_op.drop_index('ix_one_active_instance_config')

    # ### end Alembic commands ###
