"""add Source.deleted_at

Revision ID: 35513370ba0d
Revises: 523fff3f969c
Create Date: 2020-05-06 22:28:01.214359

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35513370ba0d"
down_revision = "523fff3f969c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
