"""dropped session_nonce from journalist table and revoked tokens table due to new session implementation

Revision ID: c5a02eb52f2d
Revises: d9d36b6f4d1e
Create Date: 2022-04-16 21:25:22.398189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a02eb52f2d'
down_revision = 'd9d36b6f4d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    with op.batch_alter_table('journalists', schema=None) as batch_op:
        batch_op.drop_column('session_nonce')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journalists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_nonce', sa.INTEGER(), nullable=False))

    op.create_table('revoked_tokens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('journalist_id', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['journalist_id'], ['journalists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###
