"""add instance_config key-value store

Revision ID: fef03c1ec779
Revises: 3da3fcab826a
Create Date: 2019-10-21 00:43:19.477835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef03c1ec779'
down_revision = '3da3fcab826a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_config',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance_config')
    # ### end Alembic commands ###
