
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '3.1.1'
version_full = '9452415bfeda392eb521ed5ff83d153e91f70298'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

