#!/usr/bin/python
from PyQt5 import QtWidgets
import sys

from journalist_gui.SecureDropUpdater import UpdaterApp


def main():
    app = QtWidgets.QApplication(sys.argv)
    form = UpdaterApp()
    form.show()
    app.exec_()


if __name__ == '__main__':
    main()
