#!/bin/bash
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Get Monitor server's IP
ok=""
while [ ! "$ok" ]; do
    db_input critical securedrop-app-ossec/monitor_ip || true
    db_go || true
    db_get securedrop-app-ossec/monitor_ip
    IP="$RET"
    if [[ "$IP" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        IP=($IP)
        IFS=$OIFS
        [[ ${IP[0]} -le 255 && ${IP[1]} -le 255 && ${IP[2]} -le 255 && ${IP[3]} -le 255 ]]
        ok=1
    else
        db_input critical securedrop-app-ossec/monitor_ip_continue || true
        db_go || true
        db_get securedrop-app-ossec/monitor_ip_continue
        if [ "$RET" = "false" ]; then
            exit 1
        else
            db_fset securedrop-app-ossec/monitor_ip seen false
        fi
    fi
done

db_go || true
