name: Package builds
on:
  merge_group:
  push:
    branches: ["develop", "release/**", "stg-*"]
  pull_request:
    types: ["opened", "synchronize"]

# Only build for latest push/PR unless it's main or release/
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith( github.ref, 'refs/heads/release/' ) }}

defaults:
  run:
    shell: bash

jobs:
  build-debs:
    strategy:
      matrix:
        build: [one, two]
        versions:
          - ubuntu: noble
            python: "3.12"
    # TODO: change this back to ubuntu-latest once it is consistently 24.04
    uses: ./.github/workflows/build-debs-reusable.yml
    with:
      ubuntu_version: ${{ matrix.versions.ubuntu }}
      python_version: ${{ matrix.versions.python }}
      artifact_name: ${{ matrix.versions.ubuntu }}-${{ matrix.build }}

  reproducible-debs:
    strategy:
      matrix:
        ubuntu_version: [noble]
    runs-on: ubuntu-latest
    container: debian:bookworm
    needs:
      - build-debs
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes diffoscope-minimal xz-utils \
            --no-install-recommends
      - uses: actions/download-artifact@v8
        with:
          pattern: "${{ matrix.ubuntu_version }}-*"
      - name: diffoscope
        run: |
          find . -name '*.deb' -exec sha256sum {} \;
          # FIXME: securedrop-app-code isn't reproducible
          for pkg in ossec-agent ossec-server securedrop-config securedrop-keyring securedrop-ossec-agent securedrop-ossec-server securedrop-admin
          do
              echo "Checking ${pkg} (${{ matrix.ubuntu_version }})..."
              diffoscope ${{ matrix.ubuntu_version }}-one/${{ matrix.ubuntu_version }}/${pkg}_*.deb \
                         ${{ matrix.ubuntu_version }}-two/${{ matrix.ubuntu_version }}/${pkg}_*.deb
          done
          echo "Checking securedrop-admin (trixie)..."
          diffoscope ${{ matrix.ubuntu_version }}-one/trixie/securedrop-admin_*.deb \
                     ${{ matrix.ubuntu_version }}-two/trixie/securedrop-admin_*.deb
